fix _has_rotated windows powershell.exe
martomi/chiadog pull request #216
Opened 2021-06-01 16:42 UTC by mezzovide

add missing )

2021-06-03 12:43 UTC, pieterhelsen requested changes
Thanks for spotting this bug! The first bracket is actually extraneous and can be removed. 
`f"powershell.exe Write-Host(Get-Item {str(path)}).length"`

2021-06-03 14:15 UTC, pieterhelsen approved these changes

2021-06-05 10:18 UTC, martomi approved these changes
Thanks!

2021-06-05 10:18 UTC, merged

2021-06-13 16:15 UTC, jiimbo420 commented
Thanks for fix